"""add pm2 process metrics and events

Revision ID: a6541defc7af
Revises: ace44c995def
Create Date: 2026-08-18 12:46:01.905190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6541defc7af'
down_revision: Union[str, Sequence[str], None] = 'ace44c995def'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pm2_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('process_name', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pm2_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pm2_events_process_name'), ['process_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_pm2_events_timestamp'), ['timestamp'], unique=False)

    op.create_table('pm2_process_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('pm_id', sa.Integer(), nullable=True),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('cpu', sa.Float(), nullable=False),
    sa.Column('memory_rss', sa.Integer(), nullable=False),
    sa.Column('memory_heap', sa.Integer(), nullable=False),
    sa.Column('loop_delay', sa.Float(), nullable=False),
    sa.Column('uptime_ms', sa.Integer(), nullable=False),
    sa.Column('restarts', sa.Integer(), nullable=False),
    sa.Column('unstable_restarts', sa.Integer(), nullable=False),
    sa.Column('mysql_connections', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pm2_process_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pm2_process_metrics_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_pm2_process_metrics_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pm2_process_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pm2_process_metrics_timestamp'))
        batch_op.drop_index(batch_op.f('ix_pm2_process_metrics_name'))

    op.drop_table('pm2_process_metrics')
    with op.batch_alter_table('pm2_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pm2_events_timestamp'))
        batch_op.drop_index(batch_op.f('ix_pm2_events_process_name'))

    op.drop_table('pm2_events')
    # ### end Alembic commands ###
